Model ACE_B14_N7_18_lap_1.1_rep, Test RSS
Test run at 2020-08-06 23:09

model file: ../../models/ACE_B14_N7_18_lap_1.1_rep/model.py
============================================================
Traceback (most recent call last):
  File "../../../scripts/run-model-test.py", line 108, in <module>
    sys.stdout.write(open(model_file).read())
FileNotFoundError: [Errno 2] No such file or directory: '../../models/ACE_B14_N7_18_lap_1.1_rep/model.py'
